export default {
  login: '/login',
  signup: '/signup',
  submitform: '/submitform',
  submitfeedback: '/submitfeedback',
  getFormById: '/getFormById',
  getLatestForm: '/getLatestForm',
  getForm: '/getForm',
  home: '/',
  users: '/users',
  status: '/status',
  setup: '/setup',
  allClassesFeedback: '/classes',
  anyDayFeedback: '/lastclass',
  getBatches: '/getBatches',
  emailConfirmation: '/confirmation',
  resendToken: '/resend',
  batches: '/batches',
  feedbacks: '/feedbacks',
  students: '/students',
};
